name: Gemini API Proxy

on:
  repository_dispatch:
    types: [gemini-request]

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Gemini API
        id: call_api
        uses: actions/github-script@v6
        with:
          script: |
            const payload = context.payload.client_payload;
            const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${process.env.GEMINI_API_KEY}`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(payload.body)
            });
            const data = await response.json();
            if (!response.ok) {
              console.error('API Error:', data);
              throw new Error(`API Error: ${response.statusText}`);
            }
            const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
            core.setOutput('gemini_response', text || "No se pudo generar el resumen.");
          env:
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Create Response File
        run: echo '${{ steps.call_api.outputs.gemini_response }}' > response.txt

      - name: Upload Response as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gemini-response-artifact
          path: response.txt
